apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam:::role/eksctl-resilient-cluster-nodegroup-NodeInstanceRole-5tirUKB4AGUK
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam:::role/EKS-Admin-Role
      username: eks-admin-role
      groups:
        - system:masters
