apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: recommendation-pod-kill-final
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: fixed-percent
  value: "50"
  duration: "5m"
  selector:
    namespaces:
      - default
    labelSelectors:
      app: recommendationservice
