apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: checkout-slo-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: checkout.rules
    rules:
    - alert: CheckoutServiceHighErrorRate
      expr: sum(rate(http_requests_total{job="checkoutservice", code=~"[45].."}[5m])) / sum(rate(http_requests_total{job="checkoutservice"}[5m])) > 0.05
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: High error rate on Checkout Service
        description: "The checkout service has an error rate exceeding 5% for the last minute."
